- name: Create user paulus
  user:
    name: paulus
    shell: /bin/bash
    groups: sudo

- name: Configure home for paulus
  copy:
    src: home/
    dest: /home/paulus
    owner: paulus
    group: paulus

- name: Configure home for root
  copy:
    src: home/
    dest: /root

- name: Configure etc
  copy:
    src: etc/
    dest: /etc
